{% set name = "anaconda-ai" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda_ai-{{ version }}.tar.gz
  sha256: 6a630a89c5b66499d423f12757ff4cb4facb4a0d64add78d5926894bcdc5094a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true #[py<39]

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python
    - anaconda-auth >=0.13.0
    - anaconda-cli-base >=0.8.1
    - rich
    - pydantic >=2
    - typer
    - ruamel.yaml
    - openai
    - platformdirs
    - packaging
  run_constrained:
    - langchain-openai >=0.2.8
    - llm >=0.22
    - mcp >=1.26
    - pydantic-ai >=1.50

test:
  imports:
    - anaconda_ai
    - anaconda_ai.cli
    - anaconda_ai.clients
    - anaconda_ai.config
  commands:
    - pip check
  requires:
    - pip
    # 'anaconda-auth' depends on 'anaconda-anon-usage'
    # 'anaconda-anon-usage' requires 'conda' installed
    # Otherwise, 'pip check' test fails
    - conda >=23.9.0

about:
  home: https://anaconda.cloud
  summary: Download, launch, and integrate AI models curated by Anaconda
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  description: |
    Download, launch, and integrate AI models curated by Anaconda
  doc_url: https://anaconda.cloud/docs/cli/commands/anaconda-ai.html
  dev_url: https://github.com/anaconda/anaconda-ai

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - nbeerbower
